### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by annevk** [sbingler/Origin-Bound-Cookies#1]
How about just scheme-bound cookies? Everything else seems to be optional and not guaranteed, but this does essentially obsolete the need for `Secure`.

By the way, I think it would help to spell out more clearly that `__Secure-` is the (sole?) reason why the `Secure` attribute still needs to be processed to some extent in user agents that implement this proposal.

**Comment by sbingler** [comment]
Thanks for your feedback.

Definitely not an unreasonable option (and the name of the proposal this was built off of), but I'd still like to highlight the changes for default cookies somehow. I lightheartedly suggested "origin-bound cookies by default" but I'm warming to the name slightly now.

> I think it would help to spell out more clearly that __Secure- is the (sole?) reason why the Secure attribute still needs to be processed to some extent in user agents that implement this proposal.

I think you are correct after a bit of thought, but I don't think I follow how spelling that out helps? This proposal has no intent of touching `Secure` either through deprecation or modification and states as much, even if it does mostly obsolete it.

**Comment by annevk** [comment]
"Origin-bound cookies by default" seems reasonable as well.

---

Spelling it out helps because it makes it clear why it does not obsolete it. I initially had the impression that it would and the proposal was just being unnecessarily confusing.

**Comment by sbingler** [comment]
> Spelling it out helps because it makes it clear why it does not obsolete it. I initially had the impression that it would and the proposal was just being unnecessarily confusing.

Ah, I see what you mean now. Thanks for clarifying

**Comment by sbingler** [comment]
It's been a week+ without any more input on this issue, so I think it's safe to close.

The proposal's name has been updated to "Origin-Bound Cookie (by default)" and now has a tl;dr which together will hopefully prevent more confusion in the future!
